---
- name: "Play to deprovision argo"

  hosts: localhost
  connection: local

  # Only if not provided
  vars_prompt:
    - name: namespace
      prompt: "Namespace"
      private: false

  tasks:
    - name: "delete argo workflow resources"
      tags:
        - argo
        - argo-workflows
      command: >-
        oc delete -n {{ namespace }} all \
          -l ansible/role=argo-workflows \
          -l ansible/overlay=openshift
